#pragma once
#include <PicoPinHelpers.h>

#define DEVBOARD_SCLK_PIN 2u
#define DEVBOARD_MOSI_PIN 3u
#define DEVBOARD_MISP_PIN 4u
#define DEVBOARD_CS_PIN 5u
#define DEVBOARD_DC_PIN 6u
#define DEVBOARD_RST_PIN 7u
#define DEVBOARD_SDA_I2C_PIN GPIO_I2C_SDA_PIN
#define DEVBOARD_SCL_I2C_PIN GPIO_I2C_SCL_PIN
#define DEVBOARD_TPRST_PIN 10u
#define DEVBOARD_TPINT_PIN 11u
#define DEVBOARD_RGB_PIN 12u
#define DEVBOARD_BEEPER_PIN 13u
#define DEVBOARD_BUTTON1_PIN 14u
#define DEVBOARD_BUTTON2_PIN 15u
#define DEVBOARD_LED1_PIN 16u
#define DEVBOARD_LED2_PIN 17u

#define DEVBOARD_ERROR_LED_PIN DEVBOARD_LED2_PIN